name: district_navigation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  path_provider: ^2.1.5
  xml: ^6.6.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.5
  flutter_native_splash: ^2.4.3
  google_mobile_ads: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#1A1A2E"
  image: assets/splash/splash.png
  color_dark: "#1A1A2E"
  image_dark: assets/splash/splash.png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#1A1A2E"
    color: "#1A1A2E"